# Generated by Django 5.2.8 on 2025-11-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='places/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('best_time', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('review', models.TextField()),
                ('category', models.ManyToManyField(related_name='places', to='places.category')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='attractions/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='places.place')),
            ],
        ),
    ]
