# Generated by Django 5.2.8 on 2025-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='liked_places',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='places.place'),
        ),
    ]
